[[refarch_details]]
== Conclusion

Red Hat solutions involving the OpenShift Container Platform are created to deliver a production-ready foundation that simplifies the deployment process, shares the latest best practices, and provides a stable highly available environment on which to run your production applications.

This reference architecture covered the following topics:

* A completely provisioned infrastructure in AWS
* OpenShift Masters in Multiple Availability Zones
* Infrastructure nodes in Multiple Availability Zones with Router and Registry pods scaled accordingly
* Native integration with AWS services like route53, ebs, S3, IAM, ec2
** Elastic Load Balancers for the Master instances and for the Infrastructure instances
** S3 storage for persistent storage of container images
** EBS storage for /var/lib/docker on each node
** A role assigned to instances that will allow OpenShift to mount EBS volumes
* Creation of applications
* Validating the environment
* Testing failover

For any questions or concerns, please email refarch-feedback@redhat.com and ensure to visit the http://red.ht/1IEYbQT[Red Hat Reference Architecture] page to find about all of our Red Hat solution offerings. 

// vim: set syntax=asciidoc:
